export const teamData = [
    { 
        "key" : 1,
       "title" : "RAHUL",
        "line" : "-------------------",
        "name" : "TEAM LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },

    {
        "key" : 2,
        "title" : "KIRAN",
        "line" : "-------------------",
        "name" : "TEAM LEAD",
        "img" : "https://images.unsplash.com/photo-1569335048491-5fb94951e885?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 3,
        "line" : "---------------------------",
        "title" : "SHASHANK",
        "name" : "SOFTWARE LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 4,
        "line" : "---------------------------",
        "title" : "SHRAVASTI",
        "name" : "SOFTWARE LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 5,
        "line" : "---------------------------",
        "title" : "ADITYA",
        "name" : "SOFTWARE LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 6,
        "line" : "--------------------------------",
        "title" : "DHANUSH",
        "name" : "ELECTRONICS LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 7,
        "line" : "--------------------------------",
        "title" : "ANVAY",
        "name" : "ELECTRONICS LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 8,
        "line" : "--------------------------------",
        "title" : "ARJUN",
        "name" : "MECHANICAL LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 9,
        "line" : "----------------------------",
        "title" : "SAKSHAM",
        "name" : "TECHNICAL LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 10,
        "line" : "----------------------------",
        "title" : "ROHITH",
        "name" : "EVENT MANAGER",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 11,
        "line" : "--------------------------------",
        "title" : "SWETHA",
        "name" : "DESIGN TEAM LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 12,
        "line" : "--------------------------------",
        "title" : "KRITHIKA",
        "name" : "DESIGN TEAM LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 13,
        "line" : "---------------------------------",
        "title" : "MUTHU",
        "name" : "SPONSORSHIP LEAD",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
    {
        "key" : 14,
        "line" : "-----------------------------------------",
        "title" : "KRISHNA",
        "name" : "INVENTORY & LOGISTICS",
        "img" : "https://images.unsplash.com/photo-1554620121-59e7f3f6e3a4?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=800&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE0NTg5fQ",
    },
]
